websites = {
    'Food Basics': 'https://ecirculaire.foodbasics.ca/flyers/foodbasics-flyer/grid_view/661019',
    'FreshCo': 'https://flyers.freshco.com/flyers/freshco-flyer/grid_view/656515',
    'Metro':  'https://ecirculaire.metro.ca/flyers/metro-flyer/grid_view/663149',
    'Loblaws': 'https://flyers.loblaws.ca/flyers/loblaws-dryrun/grid_view/650023',
    'No Frills': 'https://flyers.nofrills.ca/flyers/nofrills-weeklyflyer/grid_view/650453',
    'Giant Tiger': 'https://eflyers.gianttiger.com/flyers/gianttiger-weeklyflyer/grid_view/650424',
    'Walmart': 'https://flyers.walmart.ca/flyers/walmartcanada-groceryflyer/grid_view/651584',
    'Shoppers Drug Mart': 'https://flyers.shoppersdrugmart.ca/flyers/shoppersdrugmart/grid_view/650453',
    'Real Canadian Superstore': 'https://flyers.realcanadiansuperstore.ca/flyers/realcanadiansuperstore/grid_view/650453',
    'Sobeys': 'https://flyers.sobeys.com/flyers/sobeys-flyer/grid_view/656515',
    'Foodland': 'https://flyers.sobeys.com/flyers/foodland-flyer/grid_view/660825',
    'Zehrs': 'https://flyers.zehrs.ca/flyers/zehrs-weeklyflyer/grid_view/650155',
    'Fortinos': 'https://flyers.fortinos.ca/flyers/fortinos-dryrun/grid_view/650044',
    'Valumart': 'https://flyers.valumart.ca/flyers/valumart-dryrun/grid_view/650044',
    'T&T': 'https://flyers.loblaws.ca/flyers/tntsupermarket-dryrun/grid_view/650044',
    'Freshmart': 'https://flyers.loblaws.ca/flyers/freshmart-dryrun/grid_view/650044',
    'Independent': 'https://flyers.loblaws.ca/flyers/yourindependentgrocer-dryrun/grid_view/650044',
    'Super C': 'https://ecirculaire.metro.ca/flyers/superc-flyer/grid_view/663149',
    'Extra Foods': 'https://flyers.loblaws.ca/flyers/extrafoods-dryrun/grid_view/650044',
    'Farm Boy': 'https://flyers.sobeys.com/flyers/farmboy-flyer/grid_view/656515',
    'Longos': 'https://flyers.sobeys.com/flyers/longos-flyer/grid_view/656515'
}

stores = [
    'Food Basics',
    'FreshCo', 
    'Metro', 
    'Loblaws', 
    'No Frills', 
    'Giant Tiger', 
    'Walmart'
]

vegan_keywords = [
    'violife',
    'daiya',
    'gardein',
    'silk',
    'yves', 
    'just plant', 
    'plant egg', 
    'just egg', 
    'plant based', 
    'beefless', 
    'cheese-style', 
    'chickenless',
    'beyond meat', 
    'sol cuisine', 
    'earths own', 
    'blue diamond', 
    'boca', 
    'sunrise soya', 
    'fontaine', 
    'sunrise soft', 
    'lightlife',
    'field roast', 
    'so delicious', 
    'oat yeah', 
    'plant-based', 
    'plant based', 
    'vegan', 
    'vegetalien', 
    'tofu', 
    'wholly veggie', 
    'zoglos', 
    'tempeh',
    'almond milk', 
    'seitan', 
    'veggie ground', 
    'veggie meat', 
    'meat replacement',
    "chick'n", 
    'vio life', 
    'unmeatable', 
    'nut cheese', 
    'cashew cheese', 
    'cashew spread', 
    'big mountain',
    'tofurky',
    'chao',
    'sweets from the earth',
    'earth island',
    'cashew dip',
    'zhoug',
    'crabless',
    'fishless',
    'miyokos',
    "miyoko's",
    'miyoko',
    'nuts for cheese',
    'fauxmagerie',
    'vegetarian',
    'non-dairy',
    'dairy free',
    'nuts for butter',
    'becel',
    'beyond burger',
    'beyond sausage',
    'beyond chicken',
    'beyond ground',
    'beyond beef',
    'meatless'
]

meat_keywords = [
    'salami',
    'turkey',
    'sardines',
    'quiche',
    'cheese',
    'salmon',
    'bacon',
    'beef',
    'chicken',
    'ice cream',
    'milk',
    'yogurt',
    'cream',
    'egg',
    'eggs',
    'danone',
    'activia',
    'butter',
    'pizza',
    'hungry-man',
    'honey',
    'rinds',
    'cake',
    'whites',
    'fish',
    'yogourt',
    'yoplait',
    'fillets',
    'steak',
    'parlour',
    'pogo',
    'entrees',
    'iögo',
    'crema',
    'nestlé pouches',
    "i can't believe it's not butter!",
    'yop',
    'chool whip',
    'skyr',
    'cheestrings',
    'black diamond'
]

non_vegan = [
    'store made',
    'mix and match deal',
    'cheesecake',
    'pizza',
    'yoplait',
    'minigo',
    'yogurt',
    'hungry-man',
    'parmesan',
    'baby',
    'purée',
    'cheez whiz',
    'kraft dinner',
    'canned tuna',
    'online grocery'
]

foods = [
    'avocados',
    'cilantro',
    'broccoli',
    'cantaloupes',
    'cauliflower',
    'potatoes',
    'mandarins',
    'apples','cucumbers',
    'cabbages',
    'jalapeños',
    'lemons',
    'blueberries',
    'tangelos',
    'grapefruits',
    'raspberries',
    'blackberries',
    'strawberries',
    'yams',
    'dates',
    'pineapples',
    'peppers',
    'pears',
    'celery',
    'mangoes',
    'watermelons',
    'asparagus',
    'bananas',
    'peaches',
    'plums',
    'limes',
    'nectarines',
    'frozen fruit',
    'mushrooms',
    'carrots',
    'ginger',
    'garlic',
    'radishes',
    'spinach'
]

postal_codes = {
    'Kingston': 'K7L3Y2',
    'Guelph': 'N1E2L8',
    'Ottawa': 'K2A1A1',
    'Smiths Falls': 'K7A1A1',
    'Cornwall': 'K6J1A1',
    'Mississuaga': 'L5A1A1',
    'Richmond Hill': 'L4C1A1',
    'Ajax': 'L1Z1A1',
    'Toronto': 'M5A1A1',
    'Scarborough': 'M1B1A1',
    'Etobicoke': 'M8Z1A1',
    'London': 'N6A1A1',
    'Waterloo': 'N2J1A1',
    'Kitchener': 'N2N1A1',
    'Sault Ste. Marie': 'P6B1A1',
    'Thunder Bay': 'P7C1A1'
}

postal_codes = {
    'Kingston': 'K7L3Y2',
    'Guelph': 'N1E2L8'
}