 
data = [{
    'item': "campbell's soup",
    'category': 'beverages',
    'name': "Campbell's soup",
    'price': '2/ $0.99',
    'store': 'Food Basics',
    'image': 'https://cdn.flippenterprise.net/page_pdf_images/12829130/3ec43258-38bf-11ec-9112-0e7faade0358/medium',
    'story': '',
    'vegan': 'FALSE',
    'foods': ["campbell's soup"],
    'real price': 0.495,
    'location': 'guelph'},
    {
    'item': 'mr. noodles instant noodles',
    'category': 'frozen',
    'name': 'Mr. noodles instant noodles',
    'price': '2/ $1.00',
    'store': 'Metro',
    'image': 'https://cdn.flippenterprise.net/page_items/240949264/1636056009/large.jpg',
    'story': '',
    'vegan': 'FALSE',
    'foods': ['mr. noodles instant noodles'],
    'real price': 0.5,
    'location': 'guelph'},
    {
    'item': 'fuyu persimmons or kiwi',
    'category': 'produce',
    'name': 'Fuyu persimmons or kiwi',
    'price': '3/ $2.00 or $0.77',
    'store': 'No Frills',
    'image': 'https://cdn.flippenterprise.net/page_pdf_images/12829400/d65d9bbc-38c0-11ec-9ed6-0efae983d694/medium',
    'story': '',
    'vegan': 'FALSE',
    'foods': ['fuyu persimmons or kiwi'],
    'real price': 0.6666666666666666,
    'location': 'guelph'},
    {
    'item': 'bagels',
    'category': 'bakery',
    'name': 'French toast bagel',
    'price': '1',
    'store': 'Metro',
    'image': 'https://cdn.flippenterprise.net/page_items/240950455/1636056059/large.jpg',
    'story': '',
    'vegan': 'FALSE',
    'foods': ['bagels'],
    'real price': 1,
    'location': 'guelph'},
    {
    'item': 'bagels',
    'category': 'bakery',
    'name': 'Everything bagel',
    'price': '2',
    'store': 'Metro',
    'image': 'https://cdn.flippenterprise.net/page_items/240950455/1636056059/large.jpg',
    'story': '',
    'vegan': 'FALSE',
    'foods': ['bagels'],
    'real price': 2,
    'location': 'guelph'},
    {
    'item': 'bagels',
    'category': 'bakery',
    'name': 'Front street bakery sesame seed bagel',
    'price': '5',
    'store': 'Metro',
    'image': 'https://cdn.flippenterprise.net/page_items/240950455/1636056059/large.jpg',
    'story': '',
    'vegan': 'FALSE',
    'foods': ['bagels'],
    'real price': 5,
    'location': 'guelph'},
    {
    'item': 'bagels',
    'category': 'bakery',
    'name': 'Whole wheat bagel',
    'price': '4',
    'store': 'Metro',
    'image': 'https://cdn.flippenterprise.net/page_items/240950455/1636056059/large.jpg',
    'story': '',
    'vegan': 'FALSE',
    'foods': ['bagels'],
    'real price': 4,
    'location': 'guelph'},
    {
    'item': 'bagels',
    'category': 'bakery',
    'name': 'Pumpernickel bagel',
    'price': '3',
    'store': 'Metro',
    'image': 'https://cdn.flippenterprise.net/page_items/240950455/1636056059/large.jpg',
    'story': '',
    'vegan': 'FALSE',
    'foods': ['bagels'],
    'real price': 3,
    'location': 'guelph'},
    {
    'item': 'bagels',
    'category': 'bakery',
    'name': 'Poppy seed bagel',
    'price': '20',
    'store': 'Metro',
    'image': 'https://cdn.flippenterprise.net/page_items/240950455/1636056059/large.jpg',
    'story': '',
    'vegan': 'FALSE',
    'foods': ['bagels'],
    'real price': 20,
    'location': 'guelph'},
    {
    'item': 'bagels',
    'category': 'bakery',
    'name': 'Plain bagel',
    'price': '7',
    'store': 'Metro',
    'image': 'https://cdn.flippenterprise.net/page_items/240950455/1636056059/large.jpg',
    'story': '',
    'vegan': 'FALSE',
    'foods': ['bagels'],
    'real price': 7,
    'location': 'guelph'},
    {
    'item': 'bagels',
    'category': 'bakery',
    'name': 'Front street bakery cheddar cheese bagel',
    'price': '2/ $1.50',
    'store': 'Metro',
    'image': 'https://cdn.flippenterprise.net/page_items/240950455/1636056059/large.jpg',
    'story': '',
    'vegan': 'FALSE',
    'foods': ['bagels'],
    'real price': 0.75,
    'location': 'guelph'},
    {
    'item': 'bagels',
    'category': 'bakery',
    'name': 'Cinnamon raisin bagel',
    'price': '2/ $1.50',
    'store': 'Metro',
    'image': 'https://cdn.flippenterprise.net/page_items/240950455/1636056059/large.jpg',
    'story': '',
    'vegan': 'FALSE',
    'foods': ['bagels'],
    'real price': 0.75,
    'location': 'guelph'},
    {
    'item': 'bagels',
    'category': 'bakery',
    'name': 'Blueberry bagel',
    'price': '2/ $1.50',
    'store': 'Metro',
    'image': 'https://cdn.flippenterprise.net/page_items/240950455/1636056059/large.jpg',
    'story': '',
    'vegan': 'FALSE',
    'foods': ['bagels'],
    'real price': 0.75,
    'location': 'guelph'}]
    